spring:

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-gateway?useSSL=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root


  # spring cloud 相关配置
  cloud:
    # gateway相关配置
    gateway:
      # 配置允许跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
    # sentinel相关配置
    sentinel:
      transport:
        # 配置Sentinel控制台的ip和端口
        dashboard: 127.0.0.1:8080
        # 这个端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互
        port: 8099
      # 服务启动直接建立心跳连接
      eager: true

      # 路由定义
      routes:

        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1

        - id: eureka-manage
          uri: lb://eureka-manage
          predicates:
            - Path=/eureka-manage/**
          filters:
            - StripPrefix=1

        - id: sina
          uri: https://www.sina.com.cn/
          predicates:
            - Path=/sina/**
          filters:
            - StripPrefix=1


org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /baidu
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1m

management:
  endpoints:
    web:
      exposure:
        include: "*"


