kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: my-gateway
  name: my-gateway
  namespace: default
spec:
  type: NodePort
  ports:
    - name: my-gateway
      port: 30006
      targetPort: 30006
      nodePort: 30006
  selector:
    k8s-app: my-gateway
